# .github/workflows/ml-pipeline.yml
name: ML Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.4'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install dvc-gs  # Modify based on your remote

      - name: Configure DVC
        env:
          GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        run: |
          echo $GCP_SERVICE_ACCOUNT_KEY > gcp-key.json
          dvc remote add -d -f myremote gs://dvc_demo_test
          dvc remote modify myremote credentialpath gcp-key.json


      - name: Pull data from DVC remote
        run: dvc pull

      - name: Run DVC pipeline
        run: dvc repro

      - name: Push results to DVC remote
        run: dvc push

      - name: Commit and push changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update models and metrics " || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/ranjeetkumar/dvc-production-demo.git
          git push origin main
        
      
